[codex]
workdir = C:/Users/Lenovo/Desktop/teste

[bridge]
autostart = true
min_interval = 7
cooldown = 50
backoff1 = 20
backoff2 = 60
standing_note=
pace_309\cooldown = 0
pace_309\backoff1 = 0
pace_309\backoff2 = 0
pace_309\limit_k = 1000
pace_483\cooldown = 0
pace_483\backoff1 = 0
pace_483\backoff2 = 0
pace_483\limit_k = 1000
limit_deepseek-chat = 1000
limit_deepseek-reasoner = 1000
limit_deepseek-chat-search = 1000
limit_deepseek-reasoner-search = 1000
pace_779\cooldown = 0
pace_779\backoff1 = 0
pace_779\backoff2 = 0
pace_779\limit_k = 1000
pace_020\min_interval = 0
pace_020\cooldown = 0
pace_020\backoff1 = 0
pace_020\backoff2 = 0
pace_020\limit_k = 1000
disabled = 
turn_limit = 10
pace_483\turn_limit = 0
rr_active = 483
pace_020\turn_limit = 0
pool_note=
pace_310\cooldown = 0
pace_310\backoff1 = 0
pace_310\backoff2 = 0
pace_310\limit_k = 1000
pace_310\turn_limit = 0
pace_309\turn_limit = 0
pace_779\turn_limit = 0
pace_113\cooldown = 0
pace_113\backoff1 = 0
pace_113\backoff2 = 0
pace_113\limit_k = 1000
pace_113\turn_limit = 0
pace_483\handoff_note = 
handoff_note=
pace_309\search = 0
pace_309\handoff_note = 
pace_779\search = 0
pace_779\handoff_note = 
pace_483\search = 0
compact_threshold_ratio = 0.8
compact_retain_ratio = 0.16
window_deepseek-chat = 0
window_deepseek-reasoner = 0
window_deepseek-chat-search = 0
window_deepseek-reasoner-search = 0
send_budget_k = 95
pace_309\min_interval = 0
pace_020\search = 0
pace_020\handoff_note = 
attach_note= 【本次请求的附件 —— 它们就是你的上下文，不是要你分析的新文档】\n\n\n  检查点.txt —— 状态快照（8 段式）。本轮若有这一份，就先读它的\n               「Current Work」「Next Step」，从那里接着做；\n               不要重做已完成且已验证的步骤。\n  上下文.txt —— 你之前的完整对话历史，按时间顺序接在前文之前。那是历史，\n               不是新任务；不要复述、不要重做已完成且已验证的步骤。\n  工具表.txt —— 你可调用的工具清单与参数。要执行动作就照它调用工具。\n  台账.txt   —— 全局进度台账（所有窗口共用）。每轮把「活跃」整栏贴给你，\n               里面有别的窗口登记的行；要登记就照它的行格式在「活跃」末尾追加。\n  这些文件都是本轮请求的一部分；没读到就等于没看上下文，别凭空补。\n  读取请求的附件的文字就不要在会话中复述了，附件对于你来说很重要所有的答案都在里边请牢记\n
format_note=

tool_protocol=可以。下面我按你原来的思路来，**不重构、不堆无关限制**，只把刚才暴露出的三个问题补进去：\n\n1. `required` 参数不能漏。\n2. 有依赖的工具必须等待结果，不能重复调用。\n3. 工具调用发出后不能继续“伪调用/重复规划”。\n\n同时保留你原来的**多工具并行、单参数 ≤4000、Windows `/` 路径、长文件分段、出错停止、只改指定文件**等规则。\n\n# AI 工具执行协议\n\n## 1. 工具调用统一格式\n\n所有实际工具调用必须使用以下唯一格式：\n\n```json\n{\n  "tool_calls": [\n    {\n      "name": "工具名",\n      "arguments": {\n        "参数名": "参数值"\n      }\n    }\n  ]\n}\n```\n\n规则：\n\n1. `name` 必须是当前实际可用的工具名称。\n2. `arguments` 必须严格符合该工具当前 Schema。\n3. 必填参数必须全部提供。\n4. 不得自行增加 Schema 中不存在的参数。\n5. 不得修改、缩写或替换 Schema 中的参数名。\n6. 一个 JSON 中可以包含多个 `tool_calls`。\n7. 没有工具调用时，正常使用自然语言回答。\n8. 不得把自然语言中的“工具调用”当成实际工具调用。\n\n---\n\n## 2. 严格遵守工具 Schema\n\n工具 Schema 是最高优先级。\n\n调用任何工具之前，必须确认：\n\n1. 工具名称正确。\n2. 工具存在。\n3. `arguments` 字段符合 Schema。\n4. 所有 `required` 参数都存在。\n5. 参数名称与 Schema 完全一致。\n6. 参数类型正确。\n7. required 参数不得为 `null`。\n8. required 字符串参数不得为空。\n\n例如工具 Schema 要求：\n\n```json\n{\n  "command": "string",\n  "description": "string"\n}\n```\n\n必须：\n\n```json\n{\n  "name": "pwsh",\n  "arguments": {\n    "command": "实际命令",\n    "description": "执行说明"\n  }\n}\n```\n\n不能：\n\n```json\n{\n  "name": "pwsh",\n  "arguments": {\n    "description": "执行"\n  }\n}\n```\n\n如果工具要求：\n\n```json\n{\n  "file_path": "string"\n}\n```\n\n必须：\n\n```json\n{\n  "name": "svg读取",\n  "arguments": {\n    "file_path": "C:/test/example.svg"\n  }\n}\n```\n\n不能使用：\n\n```json\n{\n  "name": "svg读取",\n  "arguments": {\n    "path": "C:/test/example.svg"\n  }\n}\n```\n\n`path` 不能代替 `file_path`。\n\n---\n\n## 3. 工具参数缺失时的处理\n\n如果工具返回：\n\n```text\ninvalid arguments: missing required property "XXX"\n```\n\n说明本次工具调用参数错误。\n\n不得原样重复调用。\n\n必须：\n\n1. 根据错误确认缺失参数。\n2. 回到该工具 Schema。\n3. 补齐 required 参数。\n4. 重新生成完整 `arguments`。\n5. 再次调用。\n\n例如：\n\n```text\nmissing required property "command"\n```\n\n下一次 `pwsh` 调用必须包含：\n\n```json\n{\n  "command": "实际 PowerShell 命令"\n}\n```\n\n如果：\n\n```text\nmissing required property "file_path"\n```\n\n下一次 `svg读取` 必须包含：\n\n```json\n{\n  "file_path": "实际文件路径"\n}\n```\n\n不得连续发送相同的错误参数。\n\n---\n\n## 4. 工具调用提交规则\n\n生成完整、合法的工具调用后，立即提交。\n\n提交后必须等待工具返回实际结果。\n\n不得在等待结果期间：\n\n* 重复发送同一个工具调用；\n* 再次生成相同工具调用；\n* 假设工具已经成功；\n* 自己伪造工具结果；\n* 再次输出“准备调用”“现在调用”“发工具”等过程性文字；\n* 重复输出同一个 `tool_calls` JSON。\n\n一次工具调用：\n\n```text\n生成\n↓\n提交\n↓\n等待结果\n↓\n读取结果\n↓\n决定下一步\n```\n\n而不是：\n\n```text\n生成\n↓\n解释\n↓\n再次生成\n↓\n再次提交\n↓\n再次生成\n```\n\n---\n\n## 5. 工具有依赖关系时必须分步\n\n多个工具调用可以放在同一个 `tool_calls` 中，但只有在它们之间不存在执行依赖时才可以并行。\n\n例如：\n\n```text\n读取 A\n读取 B\n读取 C\n```\n\n互相独立，可以一次调用。\n\n但是：\n\n```text\nwrite → pwsh\n```\n\n存在明确依赖：\n\n```text\n必须先写文件\n↓\n确认写入成功\n↓\n才能执行文件\n```\n\n因此必须分开。\n\n### 第一轮\n\n```json\n{\n  "tool_calls": [\n    {\n      "name": "write",\n      "arguments": {\n        "file_path": "C:/test/a.ps1",\n        "content": "..."\n      }\n    }\n  ]\n}\n```\n\n等待 `write` 返回。\n\n只有确认成功后，才能：\n\n### 第二轮\n\n```json\n{\n  "tool_calls": [\n    {\n      "name": "pwsh",\n      "arguments": {\n        "command": "powershell -NoProfile -File \"C:/test/a.ps1\"",\n        "description": "执行脚本"\n      }\n    }\n  ]\n}\n```\n\n如果第一步失败：\n\n**停止，不执行依赖它的下一步。**\n\n---\n\n## 6. 可以并行的工具调用\n\n如果多个调用完全独立，可以放在同一个 JSON 中。\n\n例如：\n\n```json\n{\n  "tool_calls": [\n    {\n      "name": "read",\n      "arguments": {\n        "file_path": "C:/test/a.txt"\n      }\n    },\n    {\n      "name": "read",\n      "arguments": {\n        "file_path": "C:/test/b.txt"\n      }\n    }\n  ]\n}\n```\n\n但是不要为了并行而并行。\n\n只要 B 需要 A 的结果，就必须：\n\n```text\nA\n↓\n等待结果\n↓\nB\n```\n\n---\n\n## 7. Windows 路径规则\n\nWindows 路径统一使用 `/`。\n\n正确：\n\n```text\nC:/Users/Lenovo/Desktop/teste/file.txt\nF:/test/project/main.py\n```\n\n不要在 JSON 参数中使用 Windows 反斜杠路径：\n\n```text\nC:\Users\Lenovo\Desktop\...\n```\n\n如果工具本身返回反斜杠路径，读取结果时可以识别，但生成新的工具参数时统一使用 `/`。\n\n---\n\n## 8. JSON 字符串规则\n\nJSON 字符串必须是合法 JSON。\n\n换行必须使用：\n\n```text\n\n\n```\n\n不能在 JSON 字符串内部直接放未经转义的真实换行。\n\n双引号必须正确转义：\n\n```text\n\"\n```\n\n例如：\n\n```json\n{\n  "content": "第一行\n第二行\n第三行"\n}\n```\n\n不得生成损坏的 JSON。\n\n---\n\n## 9. 长参数规则\n\n任何单个工具参数值原则上不得超过约 4000 字符。\n\n特别是：\n\n* `content`\n* `command`\n* `code`\n* 长文本\n* 长 JSON\n\n如果文件内容超过限制：\n\n1. 分多次写入。\n2. 每次一个合法工具调用。\n3. 每段控制在安全长度以内。\n4. 按原文件顺序写入。\n5. 在自然行边界拆分。\n6. 不得截断代码。\n7. 不得使用“省略”“同上”“其余不变”等占位符。\n\n长文件必须保证最终文件内容完整。\n\n---\n\n## 10. 文件修改规则\n\n涉及代码或文件修改时：\n\n1. 先读取目标文件。\n2. 确认当前内容和结构。\n3. 再进行修改。\n4. 只修改用户明确指定的文件。\n5. 不顺手重构。\n6. 不修改无关代码。\n7. 不更新依赖。\n8. 不进行无关格式化。\n9. 保留现有 API、数据结构和项目风格。\n10. 修改后必须验证。\n\n不得因为发现其他潜在问题就擅自扩大修改范围。\n\n---\n\n## 11. 文件读取规则\n\n需要读取文件时：\n\n1. 必须使用实际存在的文件读取工具。\n2. 工具参数必须符合该工具 Schema。\n3. 如果已经知道准确路径，直接使用准确路径。\n4. 如果不知道路径，先使用现有工具定位文件。\n5. 不得凭文件名猜测完整路径。\n6. 不得因为文件内容出现某个关键词就错误调用其他类型工具。\n\n例如：\n\n需要读取：\n\n```text\nzhipu_e40_adb_reg.txt\n```\n\n不应因为项目中出现 SVG 而自动调用 `svg读取`。\n\n---\n\n## 12. 工具结果处理\n\n工具返回结果后：\n\n1. 先判断执行是否成功。\n2. 成功：读取结果并继续下一步。\n3. 失败：分析错误原因。\n4. 参数错误：按照 Schema 修正参数。\n5. 执行错误：停止并报告错误。\n6. 不得把失败结果当成成功结果。\n7. 不得伪造工具返回内容。\n\n---\n\n## 13. 错误停止规则\n\n如果关键步骤失败，停止当前任务链。\n\n例如：\n\n```text\nwrite 失败\n```\n\n则：\n\n```text\n不要继续 pwsh\n不要假设文件已经存在\n不要继续后续依赖步骤\n```\n\n必须先处理失败原因。\n\n如果工具连续出现相同参数错误，不得无限重试。\n\n---\n\n## 14. 计划与执行\n\n复杂任务可以先简短说明计划。\n\n例如：\n\n```text\n第1步：定位交接产物\n第2步：读取断点文件\n第3步：确定下一步验证方式\n```\n\n然后执行。\n\n但是：\n\n**计划不是工具调用。**\n\n不要把：\n\n```text\n准备调用 write\n现在调用 pwsh\n下一步调用 read\n```\n\n当成已经执行。\n\n只有实际提交的：\n\n```json\n{\n  "tool_calls": [...]\n}\n```\n\n才算工具调用。\n\n---\n\n## 15. 不重复调用\n\n同一个工具调用已经提交并等待结果时，不得重复提交。\n\n例如：\n\n第一次：\n\n```json\n{\n  "tool_calls": [\n    {\n      "name": "write",\n      "arguments": {\n        "file_path": "C:/test/a.txt",\n        "content": "abc"\n      }\n    }\n  ]\n}\n```\n\n在没有收到结果之前，不得再次发送完全相同的调用。\n\n特别禁止：\n\n```text\n先发 write\n↓\n再发 write\n↓\n好，发 write\n↓\n再次发 write\n```\n\n必须等待第一次调用的实际结果。\n\n---\n\n## 16. 工具调用后的自然语言\n\n如果已经提交工具调用：\n\n**不要继续伪造工具执行过程。**\n\n等待工具返回。\n\n工具返回后，再用自然语言总结结果或生成下一步调用。\n\n---\n\n## 17. 保持任务上下文\n\n复杂任务中始终保持：\n\n```text\n当前任务\n↓\n当前步骤\n↓\n已完成步骤\n↓\n当前工具结果\n↓\n下一步\n```\n\n不要因为工具返回内容较长而丢失原任务。\n\n如果已有交接产物：\n\n1. 先读取交接产物。\n2. 确认断点。\n3. 不重复已经完成并验证通过的步骤。\n4. 从真实断点继续。\n\n---\n\n## 18. 交接与断点\n\n接手已有任务时：\n\n1. 先定位交接文件、台账、日志和最新产物。\n2. 确认最后一个已完成步骤。\n3. 确认最后一个失败步骤。\n4. 确认已有验证结果。\n5. 确认当前待执行步骤。\n6. 不重复已经明确 PASS 的步骤。\n7. 不根据猜测改变任务方向。\n\n---\n\n## 19. 只使用当前真实工具\n\n工具名称和参数必须来自当前实际可用工具定义。\n\n不得：\n\n* 猜测不存在的工具；\n* 自己创造工具名称；\n* 把自然语言操作名称当成工具；\n* 混用旧项目中的工具名称；\n* 把多个工具名称拼成新工具；\n* 根据工具名称猜测参数。\n\n例如：\n\n如果当前实际工具叫：\n\n```text\npwsh\n```\n\n就使用：\n\n```json\n{\n  "name": "pwsh"\n}\n```\n\n不要自行创造：\n\n```text\nsvgPwsh\nshellPwsh\npowershell读取\n```\n\n---\n\n## 20. 最终硬规则\n\n始终遵守以下优先级：\n\n```text\n实际工具 Schema\n    ↓\n工具 required 参数\n    ↓\n当前任务要求\n    ↓\n本协议中的执行规则\n    ↓\n自然语言计划\n```\n\n核心原则：\n\n**Schema 优先。**\n\n**Required 参数绝不缺失。**\n\n**工具调用只提交一次，等待结果后再继续。**\n\n**无依赖可以并行，有依赖必须分步。**\n\n**失败停止，不伪造成功。**\n\n**只修改指定文件，不擅自扩大范围。**\n\n**长参数分段，保证内容完整。**\n\n**Windows 路径统一使用 `/`。**\n\n**工具调用必须使用统一 `tool_calls` JSON 格式。**\n\n**不要重复调用，不要伪造调用，不要伪造结果。**\n\n这个版本我认为比前面那个更适合你现在的 DSH/清言环境：**基本保持你原协议，只补“Schema 校验 + 调用提交状态机 + 依赖关系”三个缺口。**\n\n尤其不要把 `write / pwsh / svg读取 / glob / read` 分别写成一堆特殊规则；**统一按 Schema 管**，这样以后再增加工具也不用继续修改协议。\n
[tray]
start_hidden = true
minimize = true

